name: build with libarib25 and recdvb

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  WORKDIR: ${{ github.workspace }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true 

    - name: Build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ gcc make build-essential autoconf automake libpcsclite-dev pcscd pcsc-tools libccid pkg-config

    - name: Build libarib25
      run: |
        git submodule init && git submodule update
        cd lib/libaribb25
        cmake .
        make && sudo make install && echo "done!"

    - name: Build recdvb
      run: |
        cd lib/recdvb
        git submodule init && git submodule update
        ./autogen.sh
        ./configure --enable-b25
        make && sudo make install && echo "done!"