name: CMake with libarib25 and recdvb

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  WORKDIR: ${{ github.workspace }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true 

    - name: Build dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ gcc make build-essential autoconf automake libpcsclite-dev pcscd pcsc-tools libccid pkg-config

    - name: Build libarib25
      run: |
        cd lib/libarib25 && pwd
        cmake .
        make && ls

    - name: Build recdvd
      run: |
        cd lib/recdvd && pwd
        ./autogen.sh
        ./configure --enable-b25
        make && ls
