name: CMake with libarib25 and recdvb

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  WORKDIR: ${{ github.workspace }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true 

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ gcc make build-essential autoconf automake libpcsclite-dev pcscd pcsc-tools libccid pkg-config

    - name: Install libarib25
      run: |
        cd libarib25 && pwd
        cmake .
        make && make install

    - name: Install recdvd
      run: |
        cd recdvd && pwd
        ./autogen.sh
        ./configure --enable-b25
        make && make install
